import { defineConfig } from "@rcmade/hono-docs";

export default defineConfig({
	tsConfigPath: "./tsconfig.json",
	openApi: {
		openapi: "3.0.0",
		info: {
			title: "Harune API",
			version: "1.0.0",
			description: "API documentation for Harune",
		},
		servers: [
			{ url: "http://localhost:8787" },
			{ url: "https://api.harune.me" },
		],
	},
	outputs: {
		openApiJson: "./src/generated/openapi.json",
	},
	apis: [
		{
			name: "Metadata API",
			apiPrefix: "/metadata",
			appTypePath: "src/routes/metadata-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Fetch metadata for a URL",
					description: "Returns metadata extracted from the target URL.",
					tag: ["Metadata API"],
				},
			],
		},
		{
			name: "Handle API",
			apiPrefix: "/handle",
			appTypePath: "src/routes/handle-route.ts",
			api: [
				{
					api: "/check",
					method: "get",
					summary: "Check handle availability",
					description:
						"Checks whether the authenticated user can use a handle. The requested value is normalized to lowercase before validation. Empty values, invalid formats, and reserved handles are rejected with a validation error. When the session is missing the route returns 401. When the handle is already owned by the current user it is treated as available; when another user owns it the response is { available: false }.",
					tag: ["Handle API"],
				},
			],
		},
		{
			name: "Me API",
			apiPrefix: "/me",
			appTypePath: "src/routes/me-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Get current user app context",
					description: [
						"Returns the authenticated user's app bootstrap context.",
						"",
						"Response shape:",
						"- `user`: always present",
						"- `currentPlan`: `null` when the user has no plan",
						"- `profilePage`: `null` when the user has no owned profile page",
						"- `user.password` is never exposed",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Date fields are serialized as ISO strings",
						"- `credits` is returned as an object map",
						"",
						"Example:",
						"```json",
						"{",
						'  "currentPlan": {',
						'    "id": "plan_123",',
						'    "name": "Pro",',
						'    "codename": "pro",',
						'    "quotas": {',
						'      "permiumSupport": true,',
						'      "monthlyImages": 100,',
						'      "somethingElse": "something"',
						"    },",
						'    "default": false',
						"  },",
						'  "profilePage": {',
						'    "id": "page_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "image": "https://cdn.example.com/avatar.png"',
						"  },",
						'  "user": {',
						'    "id": "user_123",',
						'    "email": "user@example.com",',
						'    "name": "User",',
						'    "image": null,',
						'    "createdAt": "2026-05-07T00:00:00.000Z",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z",',
						'    "planId": "plan_123",',
						'    "credits": { "upload": 12 }',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Me API"],
				},
			],
		},
		{
			name: "Profile API",
			apiPrefix: "/profile",
			appTypePath: "src/routes/profile-route.ts",
			api: [
				{
					api: "/:handle",
					method: "get",
					summary: "Get profile by handle",
					description: [
						"Returns the public profile page for the requested handle.",
						"",
						"Response shape:",
						"- `page`: profile metadata such as handle, bio, and hero image",
						"- `bento`: ordered bento blocks with both `desktop` and `compact` layouts",
						"- `viewer`: session-derived ownership state",
						"",
						"Rules:",
						"- Anonymous access is allowed",
						"- `viewer.canEdit` is true only for the owner",
						"- Missing layout rows are treated as internal data errors",
						"",
						"Example:",
						"```json",
						"{",
						'  "page": {',
						'    "id": "page_123",',
						'    "userId": "user_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "role": "creator",',
						'    "bio": "Link in bio page",',
						'    "image": "https://cdn.example.com/avatar.png",',
						'    "backgroundImage": null,',
						'    "location": "Seoul",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z"',
						"  },",
						'  "bento": [],',
						'  "viewer": {',
						'    "isAuthenticated": true,',
						'    "userId": "user_123",',
						'    "canEdit": true',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Profile API"],
				},
			],
		},
	],
});
