import { defineConfig } from "@rcmade/hono-docs";

export default defineConfig({
	tsConfigPath: "./tsconfig.json",
	openApi: {
		openapi: "3.0.0",
		info: {
			title: "Harune API",
			version: "1.0.0",
			description: "API documentation for Harune",
		},
		servers: [
			{ url: "http://localhost:8787" },
			{ url: "https://api.harune.me" },
		],
	},
	outputs: {
		openApiJson: "./src/generated/openapi.json",
	},
	apis: [
		{
			name: "Metadata API",
			apiPrefix: "/metadata",
			appTypePath: "src/routes/metadata-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Fetch metadata for a URL",
					description: "Returns metadata extracted from the target URL.",
					tag: ["Metadata API"],
				},
			],
		},
		{
			name: "Handle API",
			apiPrefix: "/handle",
			appTypePath: "src/routes/handle-route.ts",
			api: [
				{
					api: "/",
					method: "patch",
					summary: "Change the current user's handle",
					description: [
						"Updates the authenticated user's canonical profile handle.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- The server trims whitespace and lowercases the submitted handle",
						"- Empty, malformed, and reserved handles are rejected with validation errors",
						"- The current user must already own a profile page",
						"- A handle owned by another user returns a conflict error",
						"- Sending the current canonical handle again is treated as a no-op and returns the current profile page",
						"- Successful responses are returned with `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Handle API"],
				},
				{
					api: "/check",
					method: "get",
					summary: "Check handle availability",
					description:
						"Checks whether the authenticated user can use a handle. The requested value is normalized to lowercase before validation. Empty values, invalid formats, and reserved handles are rejected with a validation error. When the session is missing the route returns 401. When the handle is already owned by the current user it is treated as available; when another user owns it the response is { available: false }.",
					tag: ["Handle API"],
				},
			],
		},
		{
			name: "Me API",
			apiPrefix: "/me",
			appTypePath: "src/routes/me-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Get current user app context",
					description: [
						"Returns the authenticated user's app bootstrap context.",
						"",
						"Response shape:",
						"- `user`: always present",
						"- `currentPlan`: `null` when the user has no plan",
						"- `profilePage`: `null` when the user has no owned profile page",
						"- `user.password` is never exposed",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Date fields are serialized as ISO strings",
						"- `credits` is returned as an object map",
						"",
						"Example:",
						"```json",
						"{",
						'  "currentPlan": {',
						'    "id": "plan_123",',
						'    "name": "Pro",',
						'    "codename": "pro",',
						'    "quotas": {',
						'      "permiumSupport": true,',
						'      "monthlyImages": 100,',
						'      "somethingElse": "something"',
						"    },",
						'    "default": false',
						"  },",
						'  "profilePage": {',
						'    "id": "page_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "image": "https://cdn.example.com/avatar.png"',
						"  },",
						'  "user": {',
						'    "id": "user_123",',
						'    "email": "user@example.com",',
						'    "name": "User",',
						'    "image": null,',
						'    "createdAt": "2026-05-07T00:00:00.000Z",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z",',
						'    "planId": "plan_123",',
						'    "credits": { "upload": 12 }',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Me API"],
				},
				{
					api: "/analytics",
					method: "get",
					summary: "Get current user analytics summary",
					description: [
						"Returns the authenticated owner's analytics summary for the current profile page.",
						"",
						"Response shape:",
						"- `profilePageId`: the current user's owned profile page id when analytics is ready",
						"- `state`: one of `ready`, `no-profile`, or `disabled`",
						"- `summaries`: range summaries for `today`, `7d`, and `30d`",
						"- `timezone`: the normalized server timezone used for range calculation",
						"",
						"Response states:",
						"- `ready`: analytics provider is configured and a profile page exists",
						"- `no-profile`: the authenticated user does not own a profile page yet",
						"- `disabled`: analytics provider is not configured",
						"",
						"Metric rules:",
						"- `ctr` is computed as `linkClicks / pageViews * 100` and rounded to the nearest whole number",
						"- `pageViews` can be zero; in that case `ctr` is `0`",
						"- `linkClicks` counts link-click events for the owned profile page",
						"- `series` contains time-bucketed points for the active window",
						"- `topItems` contains the most-clicked links for the active window",
						"",
						"Rules:",
						"- Requires a valid session",
						"- `x-vercel-ip-timezone` is normalized on the server",
						"- `profilePageId` always comes from the current user's owned profile page",
						"- client-supplied profile ids are ignored",
						"- `Cache-Control: no-store` is returned on successful responses",
						"- unexpected failures are mapped to `500` with the existing analytics error contract",
						"",
						"Example response:",
						"```json",
						"{",
						'  "profilePageId": "page_123",',
						'  "state": "ready",',
						'  "timezone": "Asia/Seoul",',
						'  "summaries": {',
						'    "today": {',
						'      "endAt": 1715068799999,',
						'      "label": "Today",',
						'      "startAt": 1714982400000,',
						'      "timezone": "Asia/Seoul",',
						'      "unit": "hour",',
						'      "ctr": 18,',
						'      "linkClicks": 9,',
						'      "pageViews": 50,',
						'      "changes": {',
						'        "ctr": { "absolute": 2, "direction": "up", "percent": 12.5, "previous": 16 },',
						'        "linkClicks": { "absolute": 1, "direction": "up", "percent": 12.5, "previous": 8 },',
						'        "pageViews": { "absolute": 5, "direction": "up", "percent": 11.1, "previous": 45 }',
						'      },',
						'      "previous": {',
						'        "endAt": 1714982399999,',
						'        "label": "Yesterday",',
						'        "startAt": 1714896000000,',
						'        "timezone": "Asia/Seoul",',
						'        "unit": "hour",',
						'        "ctr": 16,',
						'        "linkClicks": 8,',
						'        "pageViews": 45',
						"      },",
						'      "series": [],',
						'      "topItems": []',
						"    },",
						'    "7d": {',
						'      "endAt": 1715068799999,',
						'      "label": "Last 7 days",',
						'      "startAt": 1714464000000,',
						'      "timezone": "Asia/Seoul",',
						'      "unit": "day",',
						'      "ctr": 22,',
						'      "linkClicks": 33,',
						'      "pageViews": 150,',
						'      "changes": {',
						'        "ctr": { "absolute": 4, "direction": "up", "percent": 22.2, "previous": 18 },',
						'        "linkClicks": { "absolute": 6, "direction": "up", "percent": 22.2, "previous": 27 },',
						'        "pageViews": { "absolute": 15, "direction": "up", "percent": 11.1, "previous": 135 }',
						'      },',
						'      "previous": {',
						'        "endAt": 1714463999999,',
						'        "label": "Previous 7 days",',
						'        "startAt": 1713859200000,',
						'        "timezone": "Asia/Seoul",',
						'        "unit": "day",',
						'        "ctr": 18,',
						'        "linkClicks": 27,',
						'        "pageViews": 135',
						"      },",
						'      "series": [],',
						'      "topItems": []',
						"    },",
						'    "30d": {',
						'      "endAt": 1715068799999,',
						'      "label": "Last 30 days",',
						'      "startAt": 1712380800000,',
						'      "timezone": "Asia/Seoul",',
						'      "unit": "day",',
						'      "ctr": 24,',
						'      "linkClicks": 120,',
						'      "pageViews": 500,',
						'      "changes": {',
						'        "ctr": { "absolute": 3, "direction": "up", "percent": 14.3, "previous": 21 },',
						'        "linkClicks": { "absolute": 20, "direction": "up", "percent": 20, "previous": 100 },',
						'        "pageViews": { "absolute": 50, "direction": "up", "percent": 11.1, "previous": 450 }',
						'      },',
						'      "previous": {',
						'        "endAt": 1712380799999,',
						'        "label": "Previous 30 days",',
						'        "startAt": 1709798400000,',
						'        "timezone": "Asia/Seoul",',
						'        "unit": "day",',
						'        "ctr": 21,',
						'        "linkClicks": 100,',
						'        "pageViews": 450',
						"      },",
						'      "series": [],',
						'      "topItems": []',
						"    }",
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Me API"],
				},
			],
		},
		{
			name: "Profile API",
			apiPrefix: "/profile",
			appTypePath: "src/routes/profile-route.ts",
			api: [
				{
					api: "/:handle",
					method: "get",
					summary: "Get profile by handle",
					description: [
						"Returns the public profile page for the requested handle.",
						"",
						"Response shape:",
						"- `page`: profile metadata such as handle, bio, and hero image",
						"- `bento`: ordered bento blocks with both `desktop` and `compact` layouts",
						"- `viewer`: session-derived ownership state",
						"",
						"Rules:",
						"- Anonymous access is allowed",
						"- `viewer.canEdit` is true only for the owner",
						"- Missing layout rows are treated as internal data errors",
						"",
						"Example:",
						"```json",
						"{",
						'  "page": {',
						'    "id": "page_123",',
						'    "userId": "user_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "role": "creator",',
						'    "bio": "Link in bio page",',
						'    "image": "https://cdn.example.com/avatar.png",',
						'    "backgroundImage": null,',
						'    "location": "Seoul",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z"',
						"  },",
						'  "bento": [],',
						'  "viewer": {',
						'    "isAuthenticated": true,',
						'    "userId": "user_123",',
						'    "canEdit": true',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Profile API"],
				},
			],
		},
	],
});
