import { defineConfig } from "@rcmade/hono-docs";

export default defineConfig({
	tsConfigPath: "./tsconfig.json",
	openApi: {
		openapi: "3.0.0",
		info: {
			title: "Harune API",
			version: "1.0.0",
			description: "API documentation for Harune",
		},
		servers: [
			{ url: "https://api.harune.me" },
			{ url: "http://localhost:8787" },
		],
	},
	outputs: {
		openApiJson: "./src/generated/openapi.json",
	},
	apis: [
		{
			name: "Metadata API",
			apiPrefix: "/metadata",
			appTypePath: "src/routes/metadata-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Fetch metadata for a URL",
					description: [
						"Returns metadata extracted from the target URL.",
						"",
						"Rules:",
						"- `domain` is the normalized hostname from the resolved URL with common prefixes like `www.` removed",
						"- Supported provider URLs return the canonical R2 favicon URL instead of a fetched page favicon",
						"- GitHub profile URLs also include a provider metadata payload with the recent 60-day contribution calendar",
						"- GitHub enrichment requires `GITHUB_TOKEN`",
						"- YouTube channel URLs also include a provider metadata payload from `channels.list` and the server tries `id`, `forHandle`, and `forUsername` until one returns a channel",
						'- YouTube responses narrow `providerMetadata` to `provider: "youtube"`, `viewType: "youtube_channel"`, and a payload containing `snippet` and `statistics`',
						"- YouTube enrichment requires `YOUTUBE_API_KEY`",
						"- Non-provider URLs keep the generic metadata response and leave provider fields null",
					].join("\n"),
					tag: ["Metadata API"],
				},
			],
		},
		{
			name: "Handle API",
			apiPrefix: "/handle",
			appTypePath: "src/routes/handle-route.ts",
			api: [
				{
					api: "/",
					method: "patch",
					summary: "Change the current user's handle",
					description: [
						"Updates the authenticated user's canonical profile handle.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- The server trims whitespace and lowercases the submitted handle",
						"- Empty, malformed, and reserved handles are rejected with validation errors",
						"- The current user must already own a profile page",
						"- A handle owned by another user returns a conflict error",
						"- Sending the current canonical handle again is treated as a no-op and returns the current profile page",
						"- Successful responses are returned with `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Handle API"],
				},
				{
					api: "/check",
					method: "get",
					summary: "Check handle availability",
					description:
						"Checks whether the authenticated user can use a handle. The requested value is normalized to lowercase before validation. Empty values, invalid formats, and reserved handles are rejected with a validation error. When the session is missing the route returns 401. When the handle is already owned by the current user it is treated as available; when another user owns it the response is { available: false }.",
					tag: ["Handle API"],
				},
			],
		},
		{
			name: "Me API",
			apiPrefix: "/me",
			appTypePath: "src/routes/me-route.ts",
			api: [
				{
					api: "/",
					method: "get",
					summary: "Get current user app context",
					description: [
						"Returns the authenticated user's app bootstrap context.",
						"",
						"Response shape:",
						"- `user`: always present",
						"- `currentPlan`: `null` when the user has no plan",
						"- `profilePage`: `null` when the user has no owned profile page",
						"- `user.password` is never exposed",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Date fields are serialized as ISO strings",
						"- `credits` is returned as an object map",
						"",
						"Example:",
						"```json",
						"{",
						'  "currentPlan": {',
						'    "id": "plan_123",',
						'    "name": "Pro",',
						'    "codename": "pro",',
						'    "quotas": {',
						'      "permiumSupport": true,',
						'      "monthlyImages": 100,',
						'      "somethingElse": "something"',
						"    },",
						'    "default": false',
						"  },",
						'  "profilePage": {',
						'    "id": "page_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "image": "https://cdn.harune.me/avatar.png"',
						"  },",
						'  "user": {',
						'    "id": "user_123",',
						'    "email": "user@example.com",',
						'    "name": "User",',
						'    "image": null,',
						'    "createdAt": "2026-05-07T00:00:00.000Z",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z",',
						'    "planId": "plan_123",',
						'    "credits": { "upload": 12 }',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Me API"],
				},
				{
					api: "/analytics",
					method: "get",
					summary: "Get today's visitors for the current user",
					description: [
						"Returns today's unique visitors for the authenticated owner's current profile page.",
						"",
						"Response shape:",
						"- `visitors`: today's unique visitor count",
						"",
						"Rules:",
						"- Requires a valid session",
						"- `x-vercel-ip-timezone` is normalized on the server",
						"- the current user's owned profile page is resolved on the server",
						"- if no profile page exists or analytics is disabled, the server returns `0`",
						"- `Cache-Control: no-store` is returned on successful responses",
						"- unexpected failures are mapped to `500` with the existing analytics error contract",
						"",
						"Example response:",
						"```json",
						"{",
						'  "visitors": 17',
						"}",
						"```",
					].join("\n"),
					tag: ["Me API"],
				},
			],
		},
		{
			name: "Billing API",
			apiPrefix: "/billing",
			appTypePath: "src/routes/billing-route.ts",
			api: [
				{
					api: "/products",
					method: "get",
					summary: "List DodoPayments products",
					description: [
						"Returns the products registered in DodoPayments for frontend display.",
						"",
						"Rules:",
						"- This route is public and does not require a session",
						"- The server reads DodoPayments with the server-side API key only",
						"- Products are returned with a stable `slug` field",
						"- `slug` is derived from `metadata.slug` when present, otherwise the product id is used",
						"- The response is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Billing API"],
				},
			],
		},
		{
			name: "Profile API",
			apiPrefix: "/profile",
			appTypePath: "src/routes/profile-route.ts",
			api: [
				{
					api: "/pages",
					method: "get",
					summary: "List profile page rows",
					description: [
						"Returns every row from the `profile_page` table.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Rows are returned in `updatedAt` descending order, then `createdAt` descending order",
						"- `createdAt` and `updatedAt` are returned as ISO strings",
						"- The response includes every stored column from `profile_page`",
						"- Successful responses are returned with `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/image",
					method: "post",
					summary: "Create a presigned profile image upload",
					description: [
						"Returns a presigned R2 upload URL for a profile image or background image.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with `imageKind`, `contentType`, `contentLength`, and `imageHash`",
						"- `imageKind` must be `profile` or `background`",
						"- `contentType` must be a supported image type",
						"- `contentLength` must be 5MB or smaller",
						"- `imageHash` must be a 64-character SHA-256 hex string",
						"- The response includes the stable `imageUrl` and presigned `uploadUrl`",
						"- The response is `Cache-Control: no-store`",
						"- The uploaded object is finalized later by `PATCH /profile/image`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/image",
					method: "patch",
					summary: "Finalize a profile image slot in the database",
					description: [
						"Commits a previously uploaded profile image URL into the authenticated user's profile page row.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with `imageKind` and `imageUrl`",
						"- `imageKind` must be `profile` or `background`",
						"- `imageUrl` must point to the authenticated user's stable object key",
						"- The object must already exist in storage",
						"- Only the matching DB column is updated",
						"- The response returns the committed persisted row and is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/image",
					method: "delete",
					summary: "Delete a profile image slot object",
					description: [
						"Deletes a profile image or background image object from storage without mutating the row.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with `imageUrl`",
						"- `imageUrl` must resolve to the authenticated user's profile image namespace",
						"- The object must exist before deletion",
						"- The row is not modified",
						"- The response is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/bento/media/upload",
					method: "post",
					summary: "Create a presigned bento media upload",
					description: [
						"Returns a presigned R2 upload URL for temporary bento media.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with `bentoId`, `contentType`, `contentLength`, and `contentHash`",
						"- The bento must belong to the authenticated user",
						"- `preview:` bento uploads are presigned to the public preview object key so the later save can avoid temp-to-final copy work",
						"- `contentType` must be an image or video type",
						"- `contentLength` must be 5MB or smaller",
						"- `contentHash` must be a 64-character SHA-256 hex string",
						"- The response includes the stable object metadata and presigned `uploadUrl`",
						"- No final DB write happens here",
						"- The response is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/me",
					method: "put",
					summary: "Update my profile page",
					description: [
						"Partially updates the authenticated user's profile page.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with any subset of `name`, `location`, `role`, `bio`, `image`, and `backgroundImage`",
						"- `name`, `location`, `role`, and `bio` are normalized as trimmed strings when present",
						"- `image` and `backgroundImage` must be absolute http or https URLs when present",
						"- `null` clears a field; omitted fields are preserved",
						"- The response is a committed read of the saved profile page and is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/me/bento",
					method: "put",
					summary: "Replace my bento graph",
					description: [
						"Replaces the authenticated user's bento graph with the provided snapshot.",
						"",
						"Rules:",
						"- Requires a valid session",
						"- Accepts JSON with a `bento` array",
						"- The server deletes bentos missing from the snapshot",
						"- Each bento item must include `id`, `type`, `layout`, and type-specific `content`",
						"- Supported bento types are `link`, `text`, `section`, `media`, and `map`",
						"- Media items may include `tempObjectKey` for temp-to-final promotion, including `preview:` draft uploads",
						"- `public/.../preview:` media object keys are accepted as-is when the object already exists, including percent-encoded `preview%3A` keys from older preview uploads",
						"- `tempObjectKey` may be a legacy temp key or a public preview object key returned by upload",
						"- Existing media URLs from an older public R2 origin are accepted when their path matches `objectKey`; saved responses normalize media URLs to the current public CDN",
						"- Media `alt` may be an empty string",
						"- Temp promotion validates ownership, requires `contentHash` and `contentType`, and defers best-effort temp deletion after the response",
						"- The response returns the saved profile graph assembled from the accepted payload after the DB write and is `Cache-Control: no-store`",
					].join("\n"),
					tag: ["Profile API"],
				},
				{
					api: "/:handle",
					method: "get",
					summary: "Get profile by handle",
					description: [
						"Returns the public profile page for the requested handle.",
						"",
						"Response shape:",
						"- `page`: profile metadata such as handle, bio, and hero image",
						"- `bento`: ordered bento blocks with both `desktop` and `compact` layouts",
						"- `viewer`: session-derived ownership state",
						"",
						"Rules:",
						"- Anonymous access is allowed",
						"- `viewer.canEdit` is true only for the owner",
						"- Missing layout rows are treated as internal data errors",
						"",
						"Example:",
						"```json",
						"{",
						'  "page": {',
						'    "id": "page_123",',
						'    "userId": "user_123",',
						'    "handle": "harune",',
						'    "name": "Harune",',
						'    "role": "creator",',
						'    "bio": "Link in bio page",',
						'    "image": "https://cdn.harune.me/avatar.png",',
						'    "backgroundImage": null,',
						'    "location": "Seoul",',
						'    "updatedAt": "2026-05-07T00:00:00.000Z"',
						"  },",
						'  "bento": [],',
						'  "viewer": {',
						'    "isAuthenticated": true,',
						'    "userId": "user_123",',
						'    "canEdit": true',
						"  }",
						"}",
						"```",
					].join("\n"),
					tag: ["Profile API"],
				},
			],
		},
	],
});
